version: 1

services:
  - type: web
    name: camp-api
    runtime: docker
    repo: https://github.com/Bader-Idris/camp-api.git
    branch: bader
    rootDir: camp-api
    env:
      NODE_ENV: development
    buildCommand: docker-compose -f a.yml -f b.dev.yml build
    startCommand: docker-compose -f a.yml -f b.dev.yml up
    healthCheckPath: /health
    healthCheckTimeout: 5
    dockerfile: ./Dockerfile
    dockerCompose:
      path: ./a.yml
    # dockerCommand: ./webdis.sh # optional (defaults to Dockerfile command)
