version: 1

services:
  - name: timeapis
    env:
      NODE_ENV: development
    buildCommand: docker-compose -f a.yml -f b.dev.yml build
    startCommand: docker-compose -f a.yml -f b.dev.yml up
    healthCheckPath: /health
    healthCheckTimeout: 5
    dockerfile: ./Dockerfile
    dockerCompose:
      path: ./a.yml
